//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AukcijskaProdaja
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Auctions
    {
        public int AuctionID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> LastBid { get; set; }
        public string LastBidder { get; set; }
    }
}
