//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AukcijskaProdaja
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
    }
}
